# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.15.3-stretch

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:11.3
 
variables:
 POSTGRES_DB: wheelhouse-test
 POSTGRES_HOST: postgres
 POSTGRES_PORT: 5432
 POSTGRES_USER: postgres
 POSTGRES_PASSWORD: postgres

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test_suite:
  script:
  - npm install
  - npm i -g knex
  - knex migrate:latest --env test
  - npm test
  only:
  - master

stages:
 - build
 
variables:
 IMAGE_TAG: deranjer/wheelhouse-be:$CI_COMMIT_TAG
 
before_script:
 - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 
build:
 stage: build
 script:
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG