# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: golang:1.12.6-stretch

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:11.3
 
variables:
 POSTGRES_DB: wheelhouse-test
 POSTGRES_HOST: postgres
 POSTGRES_PORT: 5432
 POSTGRES_USER: postgres
 POSTGRES_PASSWORD: postgres

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - .cache
  
job1:
    script:
     - mkdir -p .cache
     - export GOPATH="$CI_PROJECT_DIR/.cache"
     - go mod download
     - go run main.go
    only:
     - master

test_suite:
  script:
  - go test
  only:
  - master